import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
const b='agent/src/main/';
const req=['resources/db/migration/V1__baseline.sql','resources/db/migration/V2__fixtures.sql','resources/db/migration/V8__remove_legacy_sample_fixtures.sql','java/com/monitoring/agent/AgentApplication.java','java/com/monitoring/agent/security/TokenCipher.java','java/com/monitoring/agent/collection/SsrfGuard.java','java/com/monitoring/agent/collection/CollectorClient.java','java/com/monitoring/agent/metric/StatusEvaluator.java','java/com/monitoring/agent/certificate/CertificateChecker.java'];
test('단계 3 Agent 서버 핵심 구현이 존재한다',()=>{for(const p of req)assert.equal(existsSync(b+p),true,p);});
test('Flyway는 legacy V2 checksum을 보존하고 최종 sample fixture를 제거한다',()=>{const s=readFileSync(b+'resources/db/migration/V1__baseline.sql','utf8');for(const t of ['projects','instances','instance_snapshot_latest','instance_metric_samples','disk_latest','db_pool_latest','check_definitions','check_results_latest','certificate_targets','certificate_latest','app_users','thresholds'])assert.match(s,new RegExp('CREATE TABLE '+t));const legacy=readFileSync(b+'resources/db/migration/V2__fixtures.sql','utf8');const cleanup=readFileSync(b+'resources/db/migration/V8__remove_legacy_sample_fixtures.sql','utf8');assert.match(legacy,/INSERT INTO thresholds/);assert.match(legacy,/sample-a|sample-b/);assert.match(cleanup,/DELETE FROM instances/);assert.match(cleanup,/DELETE FROM projects/);assert.equal(existsSync(b+'resources/db/migration/V2__default_thresholds.sql'),false);});
test('보안 경계는 AES-GCM, redirect 금지, 1MB, CIDR allowlist를 강제한다',()=>{assert.match(readFileSync(b+'java/com/monitoring/agent/security/TokenCipher.java','utf8'),/AES\/GCM\/NoPadding/);const c=[
  'java/com/monitoring/agent/collection/CollectorClient.java',
  'java/com/monitoring/agent/collection/HttpResponseParser.java',
].map((path)=>readFileSync(b+path,'utf8')).join('\n');assert.match(c,/MAX_RESPONSE_BYTES\s*=\s*1024 \* 1024/);assert.match(c,/REDIRECT_REJECTED/);assert.match(c,/new InetSocketAddress\(address, port\)/);const guard=readFileSync(b+'java/com/monitoring/agent/collection/SsrfGuard.java','utf8');assert.match(guard,/ResolvedTarget/);assert.match(guard,/allowedCidrs/);});
